---
- name: conditions in playbook
  hosts: all
  gather_facts: yes
  become: true
 
  tasks: 
  - name: install httpd on redhat
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    notify: start httpd service

  - name: copy index file
    copy:
      src: /home/ansible/playbooks/index.html
      dest: /var/www/html/
  
  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
      
